### ISSUE TITLE
Wrong dual operations

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/Toposes#25]
The `dual_operation`s of the `Cartesian*` operations are called `CoCartesian*`. They should be called `Cocartesian`. This is the reason for the CI failures in HigherHomologicalAlgebra.

ping @kamalsaleh

**Comment by zickgraf** [comment]
@mohamed-barakat This is already fixed, right?

**Comment by mohamed-barakat** [comment]
Yes, thanks for the ping.
