### ISSUE TITLE
Issues with headers and PackageJanitor

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/Toposes#26]
The new header `THIS FILE WAS AUTOMATICALLY GENERATED` (including the following lines) conflicts with PackageJanitor. Could you place the new header below the default header, i.e. after line 5?

**Comment by zickgraf** [comment]
@mohamed-barakat Could you have a look at this? I assume that putting the new header after line 5 should be easy by simply using `SplitString` and `JoinStringsWithSeparator`.

**Comment by zickgraf** [comment]
Now, I would suggest getting rid of the FROM und USING headers completely and putting the information in a separate file. Seeing the actual diff in PRs like #38 is very hard because of all the "boilerplate" changes -> this makes it easy to miss small but critical changes.

**Comment by mohamed-barakat** [comment]
I agree, good point.

**Comment by zickgraf** [comment]
This is still an issue, i.e. PackageJanitor still does not apply to Toposes cleanly. Could you consider the suggestion in https://github.com/homalg-project/Toposes/issues/26#issuecomment-992671714?

**Comment by mohamed-barakat** [comment]
I was unable to find an easy way to realize this, so it remained of low priority on my todo list.
